import Head from 'next/head';
import Results from '../components/Results';
import { GetServerSideProps, NextPage } from 'next';
import Header from '../components/Header';
import { Launch } from '../types';

const Home: NextPage<{ data: Launch[] }> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Space-X Launches</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Results data-testid='Results' launches={data} />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async ({ res }) => {
  try {
    const result = await fetch('https://api.spacexdata.com/v3/launches?limit=10');
    const data: Launch = await result.json();

    return {
      props: { data }
    };
  } catch {
    res.statusCode = 404;
    return {
      props: {}
    };
  }
};
